limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s;


server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
}


server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    ssl_protocols TLSv1.3;
    ssl_prefer_server_ciphers off;

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header Strict-Transport-Security "max-age=31536000" always;
    
    location /uploads/ {
        resolver 127.0.0.11 valid=30s;
        set $backend_url https://hpc-fastapi:8000;
        proxy_pass $backend_url;
        proxy_ssl_verify off;
        proxy_ssl_server_name on;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

  
    location / {
        resolver 127.0.0.11 valid=30s;
        set $frontend_url http://hpc-frontend:3000;
        
        proxy_pass $frontend_url;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        resolver 127.0.0.11 valid=30s;
        set $backend_url https://hpc-fastapi:8000;

        proxy_pass $backend_url;
        proxy_ssl_verify off;
        proxy_ssl_server_name on;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

 
    location /auth/ {
        resolver 127.0.0.11 valid=30s;
        set $keycloak_url https://hpc-keycloak:8443;
    
        proxy_pass $keycloak_url;
        proxy_ssl_verify off;
        proxy_ssl_server_name on;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
